### ISSUE TITLE
Automatic focus on the address bar (Instead of startpage)

### ISSUE THREAD

**Issue by lihuelworks** [cadejscroggins/tilde#25]
When I open the startpage, the focus of the cursor is put in the startpage itself, rather than on the adress bar. I don't know if it's intended (Since the startpage relies on it), but it hampers the use of keywords on Chrome's browser. Is it posible to change that in a way so that the startpage doesn't steal focus once it's opened? Even if it's on my side only, or if it can be edited, since maybe it doesn't require a full commit (Or can be detrimental on browsers that don't support tab-ing into the page, like Firefox)

I've checked if it was the New Tab Override extension used in Chrome, or Chrome itself, but when opening the .html file in any browser, this behavior sems to repeat.

**Comment by xvvvyz** [comment]
Interesting. Usually the idea is to give focus to the startpage so you can search/use keywords within the startpage itself 😛

However, Tilde doesn't do any explicit focus modification until you start typing. So anything that happens when you first open the page is just default browser functionality.

**Comment by xvvvyz** [comment]
Closing. Feel free to comment if you'd like to discuss more.
